// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// dotenv/config lädt standardmäßig nur ".env" — Next.js-Konvention und der Rest
// des Projekts nutzen aber ".env.local". Deshalb hier explizit geladen (Fix
// nach fehlgeschlagenem "npx prisma migrate status", 24.08.2026: Fehler
// "the URL must start with the protocol 'file:'" war Symptom davon).
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
